---
title: "STEAM Academy Overview"
---

<div class="navigation-buttons mt-4">
<a href='../index.qmd' class='btn btn-secondary'>Go Back to Home</a>
</div>

<div class="subtopic-grid">
<a href='1.-mathematical-scientific-fundamentals/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>1. Mathematical and Scientific Fundamentals</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='2.-computer-science/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>2. Computer Science</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='3.-software-development/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>3. Software Development</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='4.-artificial-intelligence-ml/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>4. Artificial Intelligence and Machine Learning</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='5.-data-science-engineering/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>5. Data Science and Engineering</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='6.-cloud-computing-devops/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>6. Cloud Computing and DevOps</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='7.-automation-low-code/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>7. Automation and Low-Code/No-Code</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='8.-innovation-emerging-trends/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>8. Innovation and Emerging Trends</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='9.-business-applications-management/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>9. Business Applications and Management</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
<a href='10.-research-academic-publications/index.qmd' class='subtopic-card'>
<span><i class='bi-file-earmark-text'></i></span>
<div>
<h4>10. Research and Academic Publications</h4>
<p>Explora los detalles de este tema clave.</p>
</div>
</a>
</div>

